export const ACTION_FETCH_FRIEND_LIST = "ACTION_FETCH_FRIEND_LIST";
export const ACTION_FETCH_FRIEND_LIST_RESULT = "ACTION_FETCH_FRIEND_LIST_RESULT";
export const ACTION_STORE_NEW_FRIEND = "ACTION_STORE_NEW_FRIEND";
export const ACTION_UPLOAD_NEW_FRIEND = "ACTION_UPLOAD_NEW_FRIEND";
export const ACTION_UPLOAD_NEW_FRIEND_RESULT = "ACTION_UPLOAD_NEW_FRIEND_RESULT";
